### ISSUE TITLE
Enumを設定する

### ISSUE THREAD

**Issue by ms2sato** [hirayama1987/bottle_stock#1]
- User#role
- Stock#amount

これらには Enumを付けてそれぞれの種類を適用できるようにしましょう。
どのような内容を付けるかは提案して欲しいです。
一度このIssue上でenumの設定を提案してもらい、合意したらコードを書きましょう。

**Comment by hirayama1987** [comment]
@ms2sato 
Enumの設定は、以下のように考えました

User#role
general_user: 0,store_user:1

Stock#amount
full: 0,half:1,small:2,ask:3

よろしくお願いいたします

**Comment by ms2sato** [comment]
@hirayama1987 ありがとうございます。

`User#role` はちょっと名前変えましょうか。
`User.general_user` のような使い方をするようになるので、`user` が重複しそうです。

general: 0, store: 1
で良さそうですね。

こちらで実装してしまいましょう。よろしくお願いします。

ちなみに、調査されましたかね。どのようなことがenumでできるようになるのか、腹落ちしてますか？
調査結果をこのIssueに貼ったり、ご自身の理解を軽くこちらで説明していただきたいです。
よろしくお願いします。

**Comment by hirayama1987** [comment]
@ms2sato 　確認ありがとうございます。
user.rbに
  enum role: { general: 0, store: 1 }
で追記したのですが、↓このようなエラーが出てしまいました。
![screencapture-localhost-3000-users-sign_up-2018-11-05-19_58_49](https://user-images.githubusercontent.com/38772465/47994349-54619e00-e135-11e8-873e-cf0dd963e7d8.png)

「store」という名前がもう使われている的なエラーなのかと思いまして、store_userにしたらエラーがなくなったのですが、どうすべきでしょうか？

enumについて調査しまして
https://www.sejuku.net/blog/26369
↑のページの
> 本来、statusをenumにて定義していなければ、battle = Battle.new(status: 0)と実装することになります。この場合"0"が何を意味するのかすぐに判断がつきません。
> しかし、サンプルコードの例のように":attack"と書いてあればコードを見ただけでどのような値か直感的にわかりやすくなります。

ここら辺で腹落ちした状態です。
DBに保存される値があらかじめ決められている場合は、enumを使って定義すると、いろんな機能が使えて、名前もつけられるから使いやすいよという理解をしています。

**Comment by ms2sato** [comment]
@hirayama1987 というわけで実装してPullRequest（PR）くださいね〜。
