### ISSUE TITLE
【調査】例外について調べる

### ISSUE THREAD

**Issue by ms2sato** [hirayama1987/bottle_stock#13]
プログラミングで「例外」という機能を使ってエラーを処理することがあります。これがどういうものか調べてこのIssueに結果をまとめてください。参考にしたURLを貼ったり、自分の言葉で説明をするなどして欲しいです。

**Comment by hirayama1987** [comment]
@ms2sato 
例外の処理について
https://qiita.com/myt732/items/42a46dcd4943ca9c0c24
https://qiita.com/murata0705/items/6ae346bd04197fb2e36a
↑ここら辺を参考に調べました。

> 何らかのエラーが発生した場合、
> そのまま Rails の英語のエラー画面を出してしまうと、
> ユーザーに無駄に悪い印象を与えてしまったりするので、
> 表側に出す用のエラー画面を用意して遷移させておく。

↑この文が意味がわかりやすかったです。

エラー用の画面の他に、エラーの内容をログに保存したり、管理者用アドレスにメールを送信して、修正対応をする。というところまで理解をしました。
