### ISSUE TITLE
ストックを作成されたタイミング で、Wishlistを持っているユーザーに「これがヒットした！」ということを知らせる

### ISSUE THREAD

**Issue by ms2sato** [hirayama1987/bottle_stock#37]
フォロー機能などをやる前に、より効果的な学習ができるこの課題をやってみましょう。

## 現状
Store側が何件ヒットしたのかは保存されるけれど、実際にwishlistを持つユーザーには何も起きません。

## 改修内容
- [ ] ヒットしたら、ヒットしたユーザーにメールを送信する
- [ ] ヒットしたら「いつ、どのwishlistにどのstockがヒットしたか」をDBに保存する
  - どのようなテーブルを用意するのかも考えて提案ください
- [ ] ヒットした履歴を一般ユーザーが見れる画面を作る（この画面からお店を知ることができる）

## 進め方
- メール送信は調べればできるのですぐ取り掛かって良いです。
- DBへの保存はこのIssue上でどのようなテーブルを作るか提案してください。合わせてから進めましょう。

**Comment by hirayama1987** [comment]
@ms2sato 
Wishhitテーブルを以下の通り考えましたので、ご確認を願いいたします。

Wishhit
・stock_id
・wishlist_id
・notice_flg (1:ユーザーがまだ確認していない、0:ユーザーが確認済み)
・created_at (自動生成されるのものを登録日として使用)

**Comment by ms2sato** [comment]
@hirayama1987 テーブルありがとうございます！

notice_flg だけちょっと気になりますね。「見た」という意味合いなら `seen` とかでも良いかもです。
